export type Label =
  | "Cine"
  | "Fiesta"
  | "Deporte"
  | "Conciertos"
  | "Gastronomía"
  | "Naturaleza"
  | "Teatro"
  | "Aventura"
  | "Evento Deportivo"
  | "Ir de Copas"
  | "Fotografía"
  | "Moda"
  | "Baile"
  | "Relax"
  | "Tomar algo"
  | "Viajes"
  | "Juegos"
  | "Tomar café";
