export const activities: { [key: string]: string } = {
  cine: "🍿 Cine",
  fiesta: "🎉 Fiesta",
  deporte: "🏋️ Deporte",
  conciertos: "🎤 Conciertos",
  concierto: "🎤 Conciertos",
  comida: "🍽️ Gastronomía",
  naturaleza: "🌳 Naturaleza",
  teatro: "🎭 Teatro",
  aventura: "🧗 Aventura",
  eventoDepor: "🏟️ Evento Deportivo",
  evento_deportivo: "🏟️ Evento Deportivo",
  copas: "🍻 Ir de copas",
  fotografia: "📸 Fotografía",
  moda: "👗 Moda",
  baile: "💃 Baile",
  relax: "🧘 Relax",
  cervezas: "🍹 Tomar algo",
  cerveza: "🍹 Tomar algo",
  viajes: "✈️ Viajes",
  juegos: "🎮 Juegos",
  cafe: "☕ Tomar un café",
};
